### PR TITLE
Development

### PR DESCRIPTION
**Pull request by akashkollipara**

### CODE REVIEW

**Comment by pranjalchanda08** [comment]
> Kudos, SonarCloud Quality Gate passed!    [Quality Gate passed](https://sonarcloud.io/dashboard?id=VisorFolks_cyancore&pullRequest=130)
> 
> [Bug](https://sonarcloud.io/project/issues?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=CODE_SMELL) [63 Code Smells](https://sonarcloud.io/project/issues?id=VisorFolks_cyancore&pullRequest=130&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=VisorFolks_cyancore&pullRequest=130&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=VisorFolks_cyancore&pullRequest=130&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=VisorFolks_cyancore&pullRequest=130&metric=new_duplicated_lines_density&view=list) [1.3% Duplication](https://sonarcloud.io/component_measures?id=VisorFolks_cyancore&pullRequest=130&metric=new_duplicated_lines_density&view=list)

What is the plan for removal of the Code Smell?

**Comment by akashkollipara** [comment]
Hmm that needs working...

**Comment by pranjalchanda08** [comment]
Its  not reliable to ignore them when we are merging to stable

**Comment by akashkollipara** [comment]
> Its not reliable to ignore them when we are merging to stable

Yes Agreed! Can you try working on them?

**Comment by akashkollipara** [comment]
> > Its not reliable to ignore them when we are merging to stable
> 
> Yes Agreed! Can you try working on them? I have few other AIs to finish.

Pushing few commits now

**Review by pranjalchanda08 — APPROVED** [review]

**Review by PoojaIngalagi — APPROVED** [review]

**Pull request merged**
